name: Generate Wallpaper
description: Create daily wallpaper
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  make-wallpaper:
    name: "Generate the wallpaper image"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: sudo apt-get install -y jq imagemagick procps
      - name:
        run: src/create_wallpaper.sh assets data
      - run: |
          git config user.name bot
          git config user.email bot@github.com
          git add -f assets/wallpaper.png
          git diff --quiet && git diff --staged --quiet || git commit -m "[gh-action] Daily Wallpaper"
          git push origin main
